import type { AdminModuleSchema } from "../shared/moduleSchema";

export const locationsModuleConfig: AdminModuleSchema = {
  id: "ubicaciones",
  titulo: "Ubicaciones y Sucursales",
  columnasOcultas: ["id"],
  etiquetas: {
    tipo_registro: "Tipo",
    nombre: "Nombre",
    descripcion: "Descripcion",
    direccion: "Direccion",
    telefono: "Telefono",
    whatsapp: "WhatsApp",
    correo: "Correo",
    horario: "Horario",
    horario_detalle: "Horario detallado",
    instagram_url: "Instagram",
    facebook_url: "Facebook",
    tiktok_url: "TikTok",
    imagen_url: "Imagen URL",
    imagen_path: "Imagen",
    notas: "Notas",
    polygon: "Poligono",
    bounds: "Limites",
    color: "Color",
    activo: "Activo",
    actualizado_en: "Actualizado",
  },
  acciones: ["ver"],
};
